import pytest


PLACEHOLDER_ROUTES = (
    # Authentication.
    ("POST", "/api/v1/auth/register"),
    ("POST", "/api/v1/auth/login"),
    ("POST", "/api/v1/auth/logout"),
    ("GET", "/api/v1/auth/me"),
    ("POST", "/api/v1/auth/refresh"),
    ("POST", "/api/v1/auth/forgot-password"),
    ("POST", "/api/v1/auth/reset-password"),
    ("POST", "/api/v1/auth/verify-email"),
    ("POST", "/api/v1/auth/resend-verification"),
    ("POST", "/api/v1/auth/change-password"),
    ("DELETE", "/api/v1/auth/account"),
    # Users.
    ("GET", "/api/v1/users/me"),
    ("PATCH", "/api/v1/users/me"),
    ("GET", "/api/v1/users/me/statistics"),
    ("GET", "/api/v1/users/me/activity"),
    ("GET", "/api/v1/users/me/notifications"),
    ("PATCH", "/api/v1/users/me/notifications/notification-1"),
    ("POST", "/api/v1/users/me/avatar"),
    ("DELETE", "/api/v1/users/me/avatar"),
    ("GET", "/api/v1/users/user-1"),
    # Topics, categories, and tags.
    ("GET", "/api/v1/topics"),
    ("POST", "/api/v1/topics"),
    ("GET", "/api/v1/topics/python-basics"),
    ("PATCH", "/api/v1/topics/topic-1"),
    ("DELETE", "/api/v1/topics/topic-1"),
    ("GET", "/api/v1/topics/topic-1/related"),
    ("GET", "/api/v1/topics/topic-1/prerequisites"),
    ("GET", "/api/v1/topics/topic-1/next"),
    ("POST", "/api/v1/topics/topic-1/publish"),
    ("POST", "/api/v1/topics/topic-1/unpublish"),
    ("GET", "/api/v1/categories"),
    ("POST", "/api/v1/categories"),
    ("GET", "/api/v1/categories/python"),
    ("PATCH", "/api/v1/categories/category-1"),
    ("DELETE", "/api/v1/categories/category-1"),
    ("GET", "/api/v1/categories/python/topics"),
    ("GET", "/api/v1/tags"),
    ("POST", "/api/v1/tags"),
    ("GET", "/api/v1/tags/asyncio"),
    ("GET", "/api/v1/tags/asyncio/topics"),
    ("DELETE", "/api/v1/tags/tag-1"),
    # Roadmap, progress, and bookmarks.
    ("GET", "/api/v1/roadmap"),
    ("GET", "/api/v1/roadmap/nodes"),
    ("GET", "/api/v1/roadmap/nodes/node-1"),
    ("GET", "/api/v1/roadmap/nodes/node-1/children"),
    ("GET", "/api/v1/roadmap/nodes/node-1/prerequisites"),
    ("GET", "/api/v1/roadmap/me"),
    ("GET", "/api/v1/roadmap/python"),
    ("PATCH", "/api/v1/roadmap/nodes/node-1"),
    ("GET", "/api/v1/progress"),
    ("GET", "/api/v1/progress/summary"),
    ("GET", "/api/v1/progress/history"),
    ("GET", "/api/v1/progress/streak"),
    ("GET", "/api/v1/progress/topic-1"),
    ("POST", "/api/v1/progress/topic-1/start"),
    ("POST", "/api/v1/progress/topic-1/complete"),
    ("PATCH", "/api/v1/progress/topic-1"),
    ("DELETE", "/api/v1/progress/topic-1"),
    ("DELETE", "/api/v1/progress/topic-1/complete"),
    ("GET", "/api/v1/bookmarks"),
    ("POST", "/api/v1/bookmarks"),
    ("GET", "/api/v1/bookmarks/bookmark-1"),
    ("DELETE", "/api/v1/bookmarks/bookmark-1"),
    ("POST", "/api/v1/bookmarks/topics/topic-1"),
    ("DELETE", "/api/v1/bookmarks/topics/topic-1"),
    ("GET", "/api/v1/bookmarks/check/topic-1"),
    ("GET", "/api/v1/bookmarks/topics/topic-1"),
    # Search, discussions, quizzes, and moderation.
    ("GET", "/api/v1/search"),
    ("GET", "/api/v1/search/suggestions"),
    ("GET", "/api/v1/search/popular"),
    ("GET", "/api/v1/search/recent"),
    ("DELETE", "/api/v1/search/recent"),
    ("GET", "/api/v1/discussions"),
    ("POST", "/api/v1/discussions"),
    ("GET", "/api/v1/discussions/discussion-1"),
    ("PATCH", "/api/v1/discussions/discussion-1"),
    ("DELETE", "/api/v1/discussions/discussion-1"),
    ("POST", "/api/v1/discussions/discussion-1/replies"),
    ("GET", "/api/v1/discussions/discussion-1/replies"),
    ("PATCH", "/api/v1/discussions/discussion-1/replies/reply-1"),
    ("DELETE", "/api/v1/discussions/discussion-1/replies/reply-1"),
    ("POST", "/api/v1/discussions/discussion-1/like"),
    ("DELETE", "/api/v1/discussions/discussion-1/like"),
    ("POST", "/api/v1/discussions/discussion-1/report"),
    ("POST", "/api/v1/discussions/replies/reply-1/report"),
    ("GET", "/api/v1/quizzes"),
    ("POST", "/api/v1/quizzes"),
    ("GET", "/api/v1/quizzes/quiz-1"),
    ("PATCH", "/api/v1/quizzes/quiz-1"),
    ("DELETE", "/api/v1/quizzes/quiz-1"),
    ("POST", "/api/v1/quizzes/quiz-1/attempts"),
    ("GET", "/api/v1/quizzes/quiz-1/attempts"),
    ("GET", "/api/v1/quizzes/attempts/attempt-1"),
    ("POST", "/api/v1/quizzes/attempts/attempt-1/answers"),
    ("POST", "/api/v1/quizzes/attempts/attempt-1/submit"),
    ("GET", "/api/v1/quizzes/attempts/attempt-1/result"),
    ("POST", "/api/v1/reports"),
    ("PATCH", "/api/v1/replies/reply-1"),
    ("DELETE", "/api/v1/replies/reply-1"),
    # Administration and media.
    ("GET", "/api/v1/admin/dashboard"),
    ("GET", "/api/v1/admin/users"),
    ("PATCH", "/api/v1/admin/users/user-1"),
    ("GET", "/api/v1/admin/users/user-1"),
    ("POST", "/api/v1/admin/users/user-1/suspend"),
    ("POST", "/api/v1/admin/users/user-1/restore"),
    ("PATCH", "/api/v1/admin/users/user-1/role"),
    ("PATCH", "/api/v1/admin/users/user-1/status"),
    ("GET", "/api/v1/admin/topics"),
    ("POST", "/api/v1/admin/topics"),
    ("PATCH", "/api/v1/admin/topics/topic-1"),
    ("DELETE", "/api/v1/admin/topics/topic-1"),
    ("GET", "/api/v1/admin/topics/pending"),
    ("POST", "/api/v1/admin/topics/topic-1/publish"),
    ("POST", "/api/v1/admin/topics/topic-1/unpublish"),
    ("GET", "/api/v1/admin/reports"),
    ("GET", "/api/v1/admin/reports/report-1"),
    ("PATCH", "/api/v1/admin/reports/report-1"),
    ("GET", "/api/v1/admin/moderation/queue"),
    ("GET", "/api/v1/admin/audit-logs"),
    ("GET", "/api/v1/admin/analytics"),
    ("GET", "/api/v1/admin/statistics"),
    ("POST", "/api/v1/media/upload"),
    ("POST", "/api/v1/media/presigned-url"),
    ("GET", "/api/v1/media/media-1"),
    ("DELETE", "/api/v1/media/media-1"),
    # HTMX fragments.
    ("GET", "/web-components/search/results"),
    ("GET", "/web-components/topic-list"),
    ("GET", "/web-components/topics/python/related"),
    ("POST", "/web-components/topics/topic-1/progress"),
    ("DELETE", "/web-components/topics/topic-1/progress"),
    ("POST", "/web-components/topics/topic-1/bookmark"),
    ("DELETE", "/web-components/topics/topic-1/bookmark"),
    ("POST", "/web-components/discussions/discussion-1/replies"),
    ("POST", "/web-components/discussions/discussion-1/like"),
    ("POST", "/web-components/discussions/discussion-1/report"),
    ("GET", "/web-components/notifications"),
    ("POST", "/web-components/notifications/notification-1/read"),
    ("GET", "/web-components/flash-messages"),
)


@pytest.mark.parametrize(("method", "path"), PLACEHOLDER_ROUTES)
def test_planned_routes_have_explicit_not_implemented_response(client, method, path) -> None:
    response = client.request(method, path, json={} if method in {"POST", "PATCH"} else None)

    assert response.status_code == 501, f"{method} {path}: {response.text}"
    assert response.json()["status"] == 501
    assert response.json()["message"].endswith("is not implemented yet")


def test_unknown_api_route_is_not_silently_accepted(client) -> None:
    response = client.get("/api/v1/does-not-exist")

    assert response.status_code == 404
